# Generated by Django 6.0.1 on 2026-04-26 08:26

from django.db import migrations


def create_teams(apps, schema_editor):
    Team = apps.get_model('teams', 'team')
    Company = apps.get_model('companies', 'company')
    companies = Company.objects.all()

    for company in companies:
        for i in range(3):
            Team.objects.get_or_create(name=f"c{company.id}Team {i}",
                                   company=company)
        
def delete_teams(apps, schema_editor):
    Team = apps.get_model('teams', 'team')
    Company = apps.get_model('companies', 'company')
    companies = Company.objects.all()

    for company in companies:
        try:
            for i in range(3):
                Team.objects.get(name=f"c{company.id}Team {i}",
                                   company=company).delete()
        except:
            ...


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('companies', '0002_create_companies')
    ]

    operations = [
        migrations.RunPython(create_teams, delete_teams)
    ]
