# Generated by Django 6.0.1 on 2026-04-19 09:03

from django.db import migrations

groups = [
        {
            'name': 'manager'
        },
        {
            'name': 'operator'
        },
        {
            'name': 'team_admin'
        },
        {
            'name': 'company_admin'
        },
        {
            'name': 'system_admin'
        }
    ]

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'group')

    for group in groups:
        Group.objects.get_or_create(name=group['name'])
    

def delete_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'group')

    for group in groups:
        try:
            Group.objects.get(name=group['name']).delete()
        except:
            ...


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial')
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups)
    ]
