# Generated by Django 6.0.1 on 2026-04-19 07:58

from django.db import migrations

actions = {
        'a':'add', 
        'v': 'view',
        'c': 'change', 
        'd': 'delete'
        }

app_permissions_templates = {
    'manager': [
        {
            'name': 'own leads',
            'content_type': 'lead',
            'codename': 'local lead',
            'actions': 'avc'
        },
        {
            'name': 'own deals',
            'content_type': 'deal',
            'codename': 'local deal',
            'actions': 'avc'
        },
        {
            'name': 'own comments',
            'content_type': 'comment',
            'codename': 'local comment',
            'actions': 'avd'
        }
    ],
    'operator': [
        {
            'name': 'team leads',
            'content_type': 'lead',
            'codename': 'team lead',
            'actions': 'avc'
        }
    ],
    'team_admin': [
        {
            'name': 'team users',
            'content_type': 'user',
            'codename': 'team user',
            'actions': 'avcd'
        },
        {
            'name': 'team leads',
            'content_type': 'lead',
            'codename': 'team lead',
            'actions': 'vc'
        },
        {
            'name': 'team comments',
            'content_type': 'comment',
            'codename': 'team comment',
            'actions': 'v'
        }
    ],
    'company_admin': [
        {
            'name': 'company teams',
            'content_type': 'team',
            'codename': 'company team',
            'actions': 'avcd'
        },
        {
            'name': 'company users',
            'content_type': 'user',
            'codename': 'company user',
            'actions': 'avcd'
        }
    ],
    'system_admin': [
        {
            'name': 'all users',
            'content_type': 'user',
            'codename': 'global user',
            'actions': 'avcd'
        },
        {
            'name': 'all companies',
            'content_type': 'company',
            'codename': 'global company',
            'actions': 'avcd'
        }
    ]
}

def create_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Company = apps.get_model('companies', 'company')
    Lead = apps.get_model('leads', 'lead')
    Deal = apps.get_model('deals', 'deal')
    Comment = apps.get_model('comments', 'comment')
    Team = apps.get_model('teams', 'team')
    User = apps.get_model('users', 'user')
    Group = apps.get_model('auth', 'group')
    lead_content_type = ContentType.objects.get_for_model(Lead)
    deal_content_type = ContentType.objects.get_for_model(Deal)
    comment_content_type = ContentType.objects.get_for_model(Comment)
    team_content_type = ContentType.objects.get_for_model(Team)
    user_content_type = ContentType.objects.get_for_model(User)
    company_content_type = ContentType.objects.get_for_model(Company)

    contenttypes = {
        'lead': lead_content_type,
        'deal': deal_content_type,
        'comment': comment_content_type,
        'team': team_content_type,
        'user': user_content_type,
        'company': company_content_type
    }

    groups = Group.objects.all()

    for group in groups:
        for template in app_permissions_templates[group.name]:
            for action_codename in template['actions']:
                action = actions[action_codename]
                codename = template['codename'].split(' ')
                codename.insert(1, action)

                p, _ = Permission.objects.get_or_create(name=f"Can {action} {template['name']}",
                                    content_type=contenttypes[template['content_type']],
                                    codename='_'.join(codename))
                
                group.permissions.add(p)
     

def delete_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Lead = apps.get_model('leads', 'lead')
    Deal = apps.get_model('deals', 'deal')
    Comment = apps.get_model('comments', 'comment')
    Team = apps.get_model('teams', 'team')
    User = apps.get_model('users', 'user')
    Group = apps.get_model('auth', 'group')
    lead_content_type = ContentType.objects.get_for_model(Lead)
    deal_content_type = ContentType.objects.get_for_model(Deal)
    comment_content_type = ContentType.objects.get_for_model(Comment)
    team_content_type = ContentType.objects.get_for_model(Team)
    user_content_type = ContentType.objects.get_for_model(User)

    contenttypes = {
        'l': lead_content_type,
        'd': deal_content_type,
        'c': comment_content_type,
        't': team_content_type,
        'u': user_content_type
    }

    groups = Group.objects.all()

    for group in groups:
        for template in app_permissions_templates[group.name]:
            for action_codename in template['actions']:
                action = actions[action_codename]
                codename = template['codename'].split(' ')
                codename.insert(1, action)

                try:
                    Permission.objects.get_or_create(name=f"Can {action} {template['name']}",
                                    content_type=contenttypes[template['content_type']],
                                    codename='_'.join(codename))
                except:
                    ...
                

class Migration(migrations.Migration):
    dependencies = [
        ('deals', '0001_initial'),
        ('comments', '0001_initial'),
        ('accounts', '0002_create_groups')
    ]

    operations = [
        migrations.RunPython(create_permissions, delete_permissions)
    ]
