# Generated by Django 6.0.1 on 2026-04-26 08:24

from django.db import migrations

companies = [
    {
        'name': 'Company 1'
    },
    {
        'name': 'Company 2'
    },
    {
        'name': 'Company 3'
    }
]

def create_companies(apps, schema_editor):
    Company = apps.get_model('companies', 'company')

    for company in companies:
        Company.objects.get_or_create(name=company['name'])

def delete_companies(apps, schema_editor):
    Company = apps.get_model('companies', 'company')

    for company in companies:
        try:
            Company.objects.get(name=company['name']).delete()
        except:
            ...


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_companies, delete_companies)
    ]
