# Generated by Django 6.0.1 on 2026-04-26 09:08

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models
from phonenumber_field.modelfields import PhoneNumberField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
        ('companies', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', PhoneNumberField(unique=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='leads', to='teams.team')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='companies.company')),
                ('source', models.CharField(choices=[('website', 'Webite'), ('call', 'Call'), ('email', 'Email'), ('ads', 'Ads')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('rejected', 'Rejected')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
                ('is_active', models.BooleanField(default=True),)
            ],
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['website', 'call', 'email', 'ads'])), name='lead_source_validation'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['new', 'contacted', 'qualified', 'rejected'])), name='lead_status_validation'),
        ),
    ]
