# Generated by Django 6.0.1 on 2026-04-26 09:04

from django.db import migrations
from ..enums import LeadSource, LeadStatus


def create_leads(apps, schema_editor):
    Lead = apps.get_model('leads', 'lead')
    User = apps.get_model('users', 'user')
    Company = apps.get_model('companies', 'company')
    companies = Company.objects.all()
    phone_template = '+12125552368'

    for company in companies:
        for team in company.teams.all():
            for i in range(2):
                u = User.objects.get(
                        email=f"managerc{company.id}t{team.id}@email.com",
                    )

                add_numbers = f'{u.id}{i}'

                phone = phone_template[:-len(add_numbers)]

                phone += add_numbers
                
                Lead.objects.get_or_create(
                    email=f"lead{i}m{u.id}c{company.id}t{team.id}@email.com",
                    defaults={
                        'full_name': f"lead{i}m{u.id}c{company.id}t{team.id}",
                        'source': LeadSource.ADS,
                        'status': LeadStatus.QUALIFIED,
                        'phone': phone,
                        'assigned_to': u,
                        'team': team
                    }
                )


def delete_leads(apps, schema_editor):
    Lead = apps.get_model('leads', 'lead')
    User = apps.get_model('users', 'user')
    Team = apps.get_model('teams', 'team')
    Company = apps.get_model('companies', 'company')
    companies = Company.objects.all()

    for company in companies:
        for team in company.teams.all():
            for i in range(2):
                try:
                    u = User.objects.get(
                        email=f"managerc{company.id}t{team.id}@email.com",
                    )
                
                    Lead.objects.get_or_create(
                        email=f"lead{i}m{u.id}c{company.id}t{team.id}@email.com"
                    ).delete()
                except:
                    ...


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('users', '0002_create_users')
    ]

    operations = [
        migrations.RunPython(create_leads, delete_leads)
    ]
