# Generated by Django 6.0.1 on 2026-05-01 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('leads', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('expected_amount', models.PositiveIntegerField()),
                ('actual_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('negotiation', 'Negotiation'), ('proposal', 'Proposal'), ('won', 'Won'), ('lost', 'Lost')], default='negotiation', max_length=50)),
                ('probability', models.PositiveIntegerField()),
                ('expected_close_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='leads.lead')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('probability__range', (0, 100))), name='probability_range_0_100'), models.CheckConstraint(condition=models.Q(('stage__in', ['negotiation', 'proposal', 'won', 'lost'])), name='stage_valid_values'), models.CheckConstraint(condition=models.Q(('closed_at__gte', models.F('created_at'))), name='closed_after_creation')],
            },
        ),
    ]
