# Generated by Django 6.0.1 on 2026-04-26 09:12

from django.db import migrations
from ..enums import DealStage

deals = [
    {
        'title': 'deal1',
        'stage': DealStage.NEGOTIAION,
        'lead': 'lead1@email.com',
        'expected_amount': 13,
        'probability': 90,
        'expected_close_date': '2026-04-30',
        'team_name': 'Team 1',
        'company_name': 'Company 1'
    }
]

def create_deals(apps, schema_editor):
    Deal = apps.get_model('deals', 'deal')
    Lead = apps.get_model('leads', 'lead')
    Company = apps.get_model('companies', 'company')
    User = apps.get_model('users', 'user')
    companies = Company.objects.all()

    for company in companies:
        for team in company.teams.all():
            for i in range(2):
                user = User.objects.get(
                    email=f"managerc{company.id}t{team.id}@email.com",
                )
                
                lead = Lead.objects.get(
                    email=f"lead{i}m{user.id}c{company.id}t{team.id}@email.com"
                )
                
                Deal.objects.get_or_create(
                    title=f"Deal{i}c{company.id}t{team.id}",
                    stage=DealStage.NEGOTIAION,
                    lead=lead,
                    expected_amount=500,
                    probability=80,
                    expected_close_date='2026-05-03',
                    company=company,
                    team=team
                )

def delete_deals(apps, schema_editor):
    Deal = apps.get_model('deals', 'deal')
    Lead = apps.get_model('leads', 'lead')
    Company = apps.get_model('companies', 'company')
    User = apps.get_model('users', 'user')
    companies = Company.objects.all()

    for company in companies:
        for team in company.teams.all():
            for i in range(3):
                try:
                    user = User.objects.get(
                        email=f"managerc{company.id}t{team.id}@email.com",
                    )
                
                    lead = Lead.objects.get(
                        email=f"lead{i}m{user.id}c{company.id}t{team.id}@email.com"
                    )
                
                    Deal.objects.get(
                        title=f"Deal{i}c{company.id}t{team.id}",
                        stage=DealStage.NEGOTIAION,
                        lead=lead,
                        expected_amount=500,
                        probability=80,
                        expected_close_date='2026-05-03',
                        company=company,
                        team=team
                    ).delete()
                except:
                    ...


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
        ('leads', '0002_create_leads'),
    ]

    operations = [
        migrations.RunPython(create_deals, delete_deals)
    ]
