# Generated by Django 6.0.1 on 2026-04-26 08:32

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_users(apps, schema_editor):
    User = apps.get_model('users', 'user')
    Group = apps.get_model('auth', 'group')
    Company = apps.get_model('companies', 'company')
    Membership = apps.get_model('accounts', 'membership')
    roles = Group.objects.all()
    companies = Company.objects.all()

    for company in companies:
        for team in company.teams.all():
            for role in roles:
                if role.name not in ['company_admin', 'system_admin']:
                    u, _ = User.objects.get_or_create(
                        email=f"{role.name}c{company.id}t{team.id}@email.com",
                        defaults={
                            'first_name': f"{role.name}",
                            'last_name': f"c{company.id}t{team.id}",
                            'role': role
                        }
                    )
                    u.password = make_password('123')
                    u.save()

                    Membership.objects.get_or_create(user=u, team=team, company=company)
            
        u, _ = User.objects.get_or_create(
                    email=f"company_adminc{company.id}@email.com",
                    defaults={
                        'first_name': f"company_admin",
                        'last_name': f"c{company.id}",
                        'role': Group.objects.get(name='company_admin')
                    }
                )
        u.password = make_password('123')
        u.save()

        Membership.objects.get_or_create(user=u, company=company)

    u, _ = User.objects.get_or_create(
            email=f"system_admin@email.com",
            defaults={
                'first_name': f"system",
                'last_name': f"admin",
                'role': Group.objects.get(name='system_admin')
            }
        )
    u.password = make_password('123')
    u.save()

def delete_users(apps, schema_editor):
    User = apps.get_model('users', 'user')
    Group = apps.get_model('auth', 'group')
    Company = apps.get_model('companies', 'company')
    Membership = apps.get_model('accounts', 'membership')
    roles = Group.objects.all()
    companies = Company.objects.all()

    for company in companies:
        try:
            for team in company.teams.all():
                for role in roles:
                    try:
                        if role not in ['company_admin', 'system_admin']:
                            u, _ = User.objects.get(
                                email=f"{role.name}c{company.id}t{team.id}@email.com"
                            ).delete()

                            Membership.objects.get(user=u, team=team, company=company).delete()
                    except:
                        ...
            
            u, _ = User.objects.get(
                        email=f"company_adminc{company.id}@email.com"
                    ).delete()

            Membership.objects.get(user=u, company=company).delete()
        except:
            ...

    try:
        u, _ = User.objects.get(
            email=f"system_admin@email.com"
        ).delete()
    except:
        ...
        


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('accounts', '0002_create_groups'),
        ('teams', '0002_create_teams')
    ]

    operations = [
        migrations.RunPython(create_users, delete_users)
    ]
